# Generated by Django 5.0 on 2025-01-16 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_likes_blog_users_who_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='users_access',
            field=models.ManyToManyField(blank=True, related_name='useres_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
